# Generated by Django 4.0.6 on 2022-07-19 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_delete_orders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='second_phone_number',
        ),
    ]
